# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
enroll:
  i_adapt_layer: 7
  adapt_layer_type: mul
  adapt_enroll_dim: 128
# Training config
training:
  epochs: 50
  batch_size: 6
  num_workers: 4
  half_lr: yes
  early_stop: yes
  reduce_patience: 20
  stop_patience: 120
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: sep_noisy
  train_dir: /nfs/data/speech-data/nm/nm_v16/train
  valid_dir: /nfs/data/speech-data/nm/nm_v15/test
  sample_rate: 16000
  n_src: 2
  segment: 3
  segment_aux: 3
